feat: update design tokens for tag
ecomfe/less-plugin-dls pull request #116
Opened 2024-06-11 11:43 UTC by xdbobname

## 11.13.0

- Adjust tokens for tags.

  - Add xs size, support 0.5px border.

2024-06-11 11:50 UTC, xdbobname commented
@code4fan

2024-06-11 12:17 UTC, Justineo requested changes

2024-06-11 12:17 UTC, Justineo commented on packages/less-plugin-dls/tokens/components/tag.less
> +@dls-tag-border-width-xs: 0.5px;
这里的逻辑是这样的，如果不同的 size 尺寸可能不一样，就得把 size 都枚举一遍，这里应该要  xs, s, m 都有。不带 size 后缀的可以保留来向前兼容。

2024-06-11 12:17 UTC, Justineo commented on packages/less-plugin-dls/tokens/components/tag.less
> +@dls-tag-padding-xs: @dls-padding-unit * 1;
同上

2024-06-11 12:17 UTC, Justineo commented on packages/less-plugin-dls/tokens/components/tag.less
> +@dls-tag-prefix-icon-spacing: @dls-padding-unit * 1;
s, m 尺寸的有 icon 吗？间距也是这个吗？如果都没有定义的话不如直接在组件库实现里面特殊处理了。

2024-06-11 12:24 UTC, xdbobname commented on packages/less-plugin-dls/tokens/components/tag.less
> +@dls-tag-border-width-xs: 0.5px;
好的 ！马上补上

2024-06-12 03:49 UTC, xdbobname commented on packages/less-plugin-dls/tokens/components/tag.less
> +@dls-tag-prefix-icon-spacing: @dls-padding-unit * 1;
都有icon, 目前使用同样的间距

2024-06-12 08:42 UTC, Justineo commented on packages/less-plugin-dls/CHANGELOG.md
> +  - Add xs size, support 0.5px border.
```suggestion
- Add `xs` size for tag.
```

2024-06-12 08:43 UTC, merged